name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd urban-eats-client
          npm install

      # - name: Run lint on all files
      #   run: |
      #     cd urban-eats-client
      #     npm run lint

      - name: Get list of changed files using git diff
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep -E '\.jsx?$')" >> $GITHUB_ENV

      - name: Debug changed files output
        run: |
          echo "Changed files: ${{ env.CHANGED_FILES }}"

      - name: Run lint on changed files
        run: |
          cd urban-eats-client
          if [ -n "$CHANGED_FILES" ]; then
            echo "$CHANGED_FILES" | xargs npm run lint --
          else
            echo "No JavaScript/JSX files were changed."
          fi
